#!/usr/bin/env bash

DirEtc=$ETC
DirEtcUbuntu=$ETC"/ubuntu"
DirEtcOSX=$ETC"/osx"

## etc files
DirVim=$DirEtc"/.vim"
Vimrc=$DirEtc"/.vimrc"
GitConf=$DirEtc"/.gitconfig"
GitIgnore=$DirEtc"/.gitignore"
RootBashrc=$DirEtc"/.bashrc-root"
Homebashrc=$DirEtc"/.bashrc-home"
Env=$DirEtc"/.env"
PrivateHosts=$DirEtc"/.PrivateHosts"
if [ $MyOS == "Darwin" ]; then
  PwdFiles=$LF"/Nutstore/config/pwd"
else
  PwdFiles=""
fi

## 
PathSync=$COMMON"/Sync"

function update_sync() {
    echo "=================etc_sync :"
    etc_sync

    export SYNCUPDATE="TRUE"
    source $PathSync
    exit
}

function etc_sync() {
    echo "$CODE :"
    cd $CODE
    git pull 
    
    cp -Rf $DirVim $LF
    cp $Vimrc $LF
    cp $GitConf $LF
    cp $GitIgnore $LF
    cp $Env $LF
    cp $PrivateHosts $LF"/.PrivateHosts"
    cp $PwdFiles $LF"/.pwd"

    if [ $MyOS != "Darwin" ]; then
      cp -Rf $DirVim /root
      cp $Vimrc /root
      cp $GitConf /root
      cp $GitIgnore /root
      cp $RootBashrc /root
      cp $HomeBashrc $LF
    fi

    source $LF/.env
}

function code_sync() {
    echo "=================code_sync :"
    echo "$BLOG :"
    cd $BLOG
    git pull

    echo "$SHLIB :"
    cd $SHLIB
    git pull

    echo "$AUTOBCT :"
    cd $AUTOBCT
    git pull

    echo "$ITOOLS :"
    cd $ITOOLS
    git pull

    export $CODEUPDATE="TRUE"
}

function main() {
    echo "===========================Start Sync========================="
    if [[ $SYNCUPDATE == "FALSE" ]]; then
        update_sync
    fi
    
    if [[ $CODEUPDATE == "FALSE" ]]; then
        code_sync
    fi
}

main
