#!/bin/bash
gArguNum=$#
gOption=$1
gAllOption="-a -d -e -p"
gFileDir=$2
gProgName=$(basename $0)
gOutputDir=""
gLogsDir="/home/liufei/log"

MORE_LOG=0

function clean_up() {
   echo "clean_up" 
   exit $1
}
#log: only write to logs.
#log -p: print to screen and write to logs.
#log -m: more log write to logs don't print to screen.
#log -e: error output to screen and logs.
function log() {
     if [[ $1 == "-p" ]]; then
       echo "$gProgName: $2" && [[ -f $gLogsDir ]] && echo "$gProgName: $2" >> $gLogsDir
     elif [[ $1 == "-e" ]]; then
       echo "$gProgName:ERROR: ${2:-"Unknown Error!"}" 1>&2 && [[ -f $gLogsDir ]] && echo "$gProgName:ERROR: ${2:-"Unknown Error!"}" >> $gLogsDir
     elif [[ $1 == "-m" && $MORE_LOG == 1 ]]; then
       [[ -f $gLogsDir ]] && echo "$gProgName: $2" >> $gLogsDir
     elif [[ $# == 1 ]]; then
       [[ -f $gLogsDir ]] && echo "$gProgName: $1" >> $gLogsDir
     fi
}

function fail() {
    log -e "$1"
    #log -e "test: log -e"
    #log -p "test: log -p"
    #log -m "test: log -m"
    #log "test: log"
    clean_up 1
}

function usage() {
    echo "usage"
}

function check_argument() {
    flag="0"
    for strOption in $gAllOption
    do
      if [[ $strOption == $gOption ]]; then
        flag="1"
      fi
    done
    #echo "$flag"

    if [[ $gArguNum == "1" && $gOption == "--help" ]]; then
      usage
    elif [[ $gArguNum == "2" && $flag == "1"  ]]; then
      if [[ -f "$gFileDir" ]]; then
        echo "Start..."
      else
        usage
        fail "don't exists file $gFileDir"
      fi
    else
      usage
      fail "bad argument!"
    fi
}

function create_output_dir() {
    echo "create_output_dir"
}

function start_analysis_clippings() {
   echo "start_analysis_clippings" 
}

function main() {
    check_argument
    create_output_dir
    start_analysis_clippings
}

main
