#!/bin/bash
gBlogName=$1
gBlogTitle=$2
gBlogCategory=$3
gBlogTags=$4
gBlogDescription=$5
gArgumentNum=$#
gBlogLink="http://liufei.name"
gRSSXML=$BLOG/atom.xml

function autoblog_help() {
    echo "eg: ./autoblog name title  category  tags  description."
}

function check_argument() {
    #echo "$gArgumentNum: $gBlogName, $gBlogTitle, $gBlogCategory, $gBlogTags, $gBlogDescription"
    if [[ $gArgumentNum != "5" ]]; then
        autoblog_help
        exit 
    fi
}

function analyse_blog(){
     ################## get bolg link ################
    temp=`echo $gBlogName | cut -d. -f1`
    tempLength=${#temp} 
    temp1=${temp:11:$temp}
    gBlogLink=$gBlogLink"/"$gBlogCategory"/"$temp1".html"
    #echo "$gBlogLink"
}

function create_blog_head() {
cat <<blog_head >$gBlogName
---
layout: post
title: $gBlogTitle
category: $gBlogCategory
tags: [$gBlogTags]
description: |
  $gBlogDescription 
---
{% include JB/setup %}

[$gBlogTitle]($gBlogLink)

blog_head
}

function write_rss_xml() {
    StrItem="  <item>"
    StrTitle="    <title>$gBlogTitle</title>"
    StrLink="    <link>$gBlogLink</link>"
    StrDescription="    <description>$gBlogDescription</description>"
    StrItem2="  </item>"

    FileLineNum=`cat $gRSSXML | wc -l`
    iNum=$(( $FileLineNum -3 ))
    temp=$iNum"i"
    #echo "$StrItem"
    #echo "$StrTitle"
    #echo "$StrLink"
    #echo "$StrDescription"
    #echo "$StrItem2"
    #echo "$temp"
    sed -i "$temp\\$StrItem\n$StrTitle\n$StrLink\n$StrDescription\n$StrItem\n" $gRSSXML
}

function main() {
    #autoblog_help
    check_argument
    analyse_blog
    create_blog_head
    write_rss_xml
}

main
