#!/bin/bash

echo "***********************************autoetc***********************************" >> /root/.lflog
DirVim=/root/.vim
DirSourceList=/etc/apt/sources.list.d

Vimrc=/root/.vimrc
RootBashrc=/root/.bashrc
HomeBashrc=/home/liufei/.bashrc
GitConf=/root/.gitconfig
GitIgnore=/root/.gitignore
Env=/home/liufei/.env
PrivateHosts=/etc/PrivateHosts
SourcesList=/etc/apt/sources.list
SourcesListSave=/etc/apt/sources.list.save

DirNameArr=("$DirVim" "$DirSourceList")
FileNameArr=("$Vimrc" "$GitConf" "$GitIgnore" "$Env" "$PrivateHosts" "$SourcesList" "$SourcesListSave")

DirEtc=$ETC

Hostname=`hostname`
Username=`sed -n '2p' $LF/.pwd | base64 -d`
Password=`sed -n '3p' $LF/.pwd | base64 -d`

function etc-bak() {
    for DirName in ${DirNameArr[@]}
    do
        if [ -d "$DirName" ]; then
            cp -R "$DirName" "$DirEtc"
        fi
    done

    if [ -f "$RootBashrc" ]; then
        cp "$RootBashrc" "$DirEtc""/.bashrc-root"
    fi

    if [ -f "$HomeBashrc" ]; then
        cp "$HomeBashrc" "$DirEtc""/.bashrc-home"
    fi

    for FileName in ${FileNameArr[@]}
    do
        cp "$FileName" "$DirEtc"
    done
}

function git-push() {
    cd $CODE
    echo `date` >> /root/.lflog
    echo "$Hostname: $CODE git-pull." >> /root/.lflog
    git pull >> /root/.lflog
    echo "$Hostname: $CODE git-push." >> /root/.lflog
    git add .
    git status >> /root/.lflog
    echo "`date`: autoetc-->commit" >> /root/.lflog
    git commit -m "`date`: autoetc."
    echo "`date`: autoetc-->push" >> /root/.lflog
    if [ "$Hostname" == "liufei-OptiPlex-360" ]; then
        local str=$(expect -c "
            spawn git push
            expect {
                -re "sername" { send \"$Username\r\"; exp_continue }
                -re "assword" { send \"$Password\r\"; }
          }
            interact
        ")
        echo "$str" >> /root/.lflog
    fi
}
etc-bak
git-push

