#!/bin/bash

echo "***********************************autoetc***********************************" >> /root/.lflog
Hostname=`hostname`
FLiu=""
if [ $Hostname = "fliu-thinkpad" ];then
  FLiu="/home/fliu"
else
  FLiu="/home/liufei"
fi

DirVim=/root/.vim

Vimrc=/root/.vimrc
RootBashrc=/root/.bashrc
HomeBashrc=$FLiu/.bashrc
GitConf=/root/.gitconfig
GitIgnore=/root/.gitignore
Env=$FLiu/.env
PrivateHosts=/etc/PrivateHosts

DirNameArr=("$DirVim")
FileNameArr=("$Vimrc" "$GitConf" "$GitIgnore" "$Env" "$PrivateHosts")

DirEtc=$ETC

Username=`sed -n '2p' $LF/.pwd | base64 -d`
Password=`sed -n '3p' $LF/.pwd | base64 -d`

function etc-bak() {
    for DirName in ${DirNameArr[@]}
    do
        if [ -d "$DirName" ]; then
            cp -R "$DirName" "$DirEtc"
        fi
    done

    if [ -f "$RootBashrc" ]; then
        cp "$RootBashrc" "$DirEtc""/.bashrc-root"
    fi

    if [ -f "$HomeBashrc" ]; then
        cp "$HomeBashrc" "$DirEtc""/.bashrc-home"
    fi

    for FileName in ${FileNameArr[@]}
    do
        cp "$FileName" "$DirEtc"
    done
}

function git-push() {
    cd $CODE
    echo `date` >> /root/.lflog
    echo "$Hostname: $CODE git-pull." >> /root/.lflog
    git pull >> /root/.lflog
    echo "$Hostname: $CODE git-push." >> /root/.lflog
    git add .
    git status >> /root/.lflog
    echo "`date`: autoetc-->commit" >> /root/.lflog
    git commit -m "`date`: autoetc."
    echo "`date`: autoetc-->push" >> /root/.lflog

        local str=$(expect -c "
            spawn git push
            expect {
                -re "sername" { send \"$Username\r\"; exp_continue }
                -re "assword" { send \"$Password\r\"; }
          }
            interact
        ")
        echo "$str" >> /root/.lflog
}
etc-bak
git-push

