#!/bin/bash

RPMName=$1
Length=${#RPMName}
TEMP=${RPMName:0:($Length-4)}
#DEBName=$TEMP".deb"
DEBName=`ls -lrt |awk -F: '{print '}|tail -n1 | awk '{print $9}'`
sudo alien -i $RPMName
sudo alien $RPMName
sudo dpkg -i $DEBName

