#!/bin/bash
##################################setup key#####################################
#chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
################################# ppa #########################################
#shutter
sudo add-apt-repository ppa:shutter/ppa

##################################更新源列表####################################
sudo apt-get update


#在右键里面 添加一个“打开终端”的菜单,需重启图形界面
sudo apt-get -y install nautilus-open-terminal
#右键中添加"以管理员身份打开"，需重启图形界面
sudo apt-get -y install nautilus-gksu

sudo apt-get -y install catfish
#rar，7z支持
sudo apt-get -y install rar
sudo apt-get -y install p7zip

sudo apt-get -y install python3.2
sudo apt-get -y install python-tk

#sudo apt-get -y install chromium-browser
sudo apt-get -y install vim
sudo apt-get -y install vim-gnome
sudo apt-get -y install git
#sudo apt-get -y install wine
sudo apt-get -y install g++
sudo apt-get -y install playonlinux
sudo apt-get -y install putty
sudo apt-get -y install cscope

sudo apt-get -y install expect
sudo apt-get -y install sl
sudo apt-get -y install alien
sudo apt-get -y install openssh-server

sudo apt-get -y install tmux
#sudo apt-get -y install byobu
sudo apt-get -y install subversion
sudo apt-get -y install automake
sudo apt-get -y install libtool

#mysql
sudo apt-get -y install libmysqlclient-dev 
sudo apt-get -y install libmysqlclient

#weibo
sudo apt-get -y install libcurl4-gnutls-dev
sudo apt-get -y install libcurl4-nss-dev
sudo apt-get -y install libcurl4-openssl-dev
sudo apt-get -y install libcppunit-dev
sudo apt-get -y install libcppunit-doc

#markdown
sudo apt-get -y install python-markdown

#ruby make 
sudo apt-get -y install rake
#Install the full Ruby package and RubyGems:
sudo apt-get install ruby-full rubygems
export REALLY_GEM_UPDATE_SYSTEM=true
gem update --system
#cloudfoundry
gem install vmc

#PDF edit
sudo apt-get -y install xournal

#htop 性能监事工具
sudo apt-get -y install htop

#打字练习
sudo apt-get -y install gtypist

#sqlite3 db
sudo apt-get -y install sqliteman

#send mail form command line

#golang
sudo apt-get -y install mercurial
sudo apt-get -y install bison

#ScheenShot:Shutter
sudo apt-get -y install Shutter

#xml viewer
#xmlcopyeditor

#多系统时更新启动项
#ubuntun10.10
#apt-get install grub2
#sudo update-grub

#重启图形界面
#ubuntu10.10
#sudo service gdm restart




