#!/bin/bash

function keynav() {
    getKeynavName=`ps -ef | grep keynav | grep -v 'grep' | awk '{print $8}'`
    #echo $getKeynavName
    if [[ -z $getKeynavName ]]; then
      keynav >/dev/null &
    fi
}

function main() {
    keynav
}

main
