#!/bin/bash

function keynav() {
    getKeynavName=`ps -ef | grep keynav | grep -v 'grep' | awk '{print $8}'`
    #echo $getKeynavName
    if [[ -z $getKeynavName ]]; then
      echo $getKeynavName
      #keynav >/dev/null &
      keynav
      getKeynavName=`ps -ef | grep keynav | grep -v 'grep' | awk '{print $8}'`
      echo $getKeynavName
    fi
}

function main() {
    keynav
}

main
