#!/bin/bash
SoftName=$1
ArguNum=$#

function setup_rpm() {
    RPMName=$SoftName
    Length=${#RPMName}
    TEMP=${RPMName:0:($Length-4)}
    sudo alien -i $RPMName
    sudo alien $RPMName
    #DEBName=$TEMP".deb"
    DEBName=`ls -lrt |awk -F: '{print '}|tail -n1 | awk '{print $9}'`
    sudo dpkg -i $DEBName
}

function setup_deb() {
    sudo dpkg -i $SoftName
}

function setup_bin() {
    chmod a+x $SoftName
    sudo ./$SoftName
}

function main() {
     if [[ $ArguNum != 1 ]]; then
        echo "only suppot rpm,deb,bin. eg:setup *.deb"
        exit
     fi
    SoftType=${SoftName##*.}
    case "$SoftType" in
        rpm) setup_rpm
             ;;
        deb) setup_deb
             ;;
        bin) setup_bin
             ;;
    tar.bz2) tar xvjf $SoftName    
             ;;
     tar.gz) tar xvzf $SoftName
             ;;
      *.bz2) bunzip2 $SoftName     
             ;;
      *.rar) unrar x $SoftName     
             ;;
       *.gz) gunzip $SoftName     
             ;;
      *.tar) tar xvf $SoftName  
             ;;
     *.tbz2) tar xvjf $SoftName   
             ;;
      *.tgz) tar xvzf $SoftName
             ;;
      *.zip) unzip $SoftName
             ;;
        *.Z) uncompress $SoftName
             ;;
       *.7z) 7z x $SoftName   
             ;;
        *)   echo "Invalid type"
    esac
}

main


