#!/bin/bash
############################################
#set 163 source
#install Chrome
#run this script
#restart computer
#set Chrome fonts size (wryh,size:18) 
#set ubuntu fonts size use unity-tweak-tool(fonts->Text scaling factor:1.05)
#set terminal size:(home:150,36)
############################################

## 
HostName=`hostname`
FLiu=""
if [ $HostName = "fliu-thinkpad" ];then
  FLiu="/home/fliu"
else
  FLiu="/home/liufei"
fi
GithubUrl="https://github.com/"
GithubUser="cheetah0216"

## Workspace
DirGithub="$FLiu/github"
DirSoft="$FLiu/soft"
DirWork="$FLiu/work"
DirCodeFonts="/usr/share/fonts/codefonts"
DirWorkSpaceArr=("$DirGithub" "$DirSoft" "$DirWork" "$DirCodeFonts")

## Prerequisite Software
SoftwareArr=("vim" "vim-gnome" "git" "expect" "wget" "unity-tweak-tool" "gconf-editor" "alien")

## Github code url
UrlCodeRespository=$GithubUrl$GithubUser"/""CodeRespository.git"
UrlBlog="$GithubUrl$GithubUser"/"$GithubUser"".github.com.git"
GithubUrlArr=("$UrlCodeRespository" "$UrlBlog")

## Set Vim 
DirVimConf=$DirGithub"/CodeRepository/tools/etc/.vim"
VimProfile=$DirGithub"/CodeRepository/tools/etc/.vimrc"

## Set Proflie
DirSource=$DirGithub"/CodeRepository/tools/etc/"

RootBashrc="/root/.bashrc"
HomeBashrc="$FLiu/.bashrc"
GitConf="/root/.gitconfig"
GitIgnore="/root/.gitignore"
Env="$FLiu/.env"
PrivateHosts="/etc/PrivateHosts"

## Set fonts
UrlFonts="http://d.pcs.baidu.com/file/c6a2fd47f7809e53325ebc59e55cdc06?fid=1258459933-250528-207959182&time=1369317409&sign=FDTAR-DCb740ccc5511e5e8fedcff06b081203-mjGdkfCYxGiZjCbZKgKkGg2LD4Q%3D&rt=sh&expires=8h&r=722107012&sh=1"

## install latest JDk
UrlJDKPages="http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html"

############
function init_workspace() {
    for DirName in ${DirWorkSpaceArr[@]}
    do
        echo $DirName
        mkdir -p $DirName
    done  
}

function install_prerequisite_soft() {
    sudo apt-get update
    for SoftWare in ${SoftwareArr[@]}
    do
        sudo apt-get -y install $SoftWare
    done
}

function get_github_code() {
    cd $DirGithub
    for CodeUrl in ${GithubUrlArr[@]}
    do
        #echo "$CodeUrl"
        git clone $CodeUrl
    done
}

function set_vim() {
    sudo apt-get -y install exuberant-ctags
    sudo apt-get -y install cscope

    cp -Rf $DirVimConf /root
    cp -Rf $DirVimConf $FLiu
    cp $VimProfile /root
    cp $VimProfile $FLiu
}

function set_profile() {
    cd $DirSource 
    cp .bashrc-root $RootBashrc
    cp .bashrc-home $HomeBashrc
    cp .gitconfig   $GitConf
    cp .gitignore   $GitIgnore
    cp .env         $Env
    cp PrivateHosts $PrivateHosts
    #gvim $RootBashrc $HomeBashrc $GitConf $GitIgnore $Env $PrivateHosts
}

function install_font() {
    cd $DirCodeFonts
    wget -O fonts.zip $UrlFonts 
    unzip fonts.zip
    sudo chmod 755 $DirCodeFonts/*
    rm fonts.zip
    sudo mkfontscale && sudo mkfontdir && sudo fc-cache -fv > /dev/null
}

function install_jdk() {
   cd /tmp
   wget -O JDK.html $UrlJDKPages
   url_latest_jdk=`cat /tmp/JDK.html | grep jdk | grep "linux-x64.tar.gz" | cut -d\" -f12`
   latest_jdk_name=${url_latest_jdk##*/}
   #echo $url_latest_jdk
   #echo $latest_jdk_name
   wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com" $url_latest_jdk -O $latest_jdk_name
   rm /tmp/JDK.html
   mv $latest_jdk_name /usr/local/
   cd /usr/local/
   tar zxvf $latest_jdk_name
   jdk_dir=`ls -lrt |awk -F: '{print '}|tail -n2 | awk '{print $9}' | grep -v ".tar.gz"`
   #echo $jdk_dir
   ln -s $jdk_dir jdk
   sudo update-alternatives --install "/usr/bin/java" "java" "/usr/local/jdk/bin/java" 1
   sudo update-alternatives --install "/usr/bin/javac" "javac" "/usr/local/jdk/bin/javac" 1
   sudo update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/local/jdk/bin/javaws" 1
   sudo update-alternatives --install "/usr/lib/mozilla/plugins/libjavaplugin.so" "mozilla-javaplugin.so" "/usr/local/jdk/jre/lib/amd64/libnpjp2.so" 1
   sudo update-alternatives --config java
   sudo update-alternatives --config javac
   sudo update-alternatives --config javaws
   #export JAVA_HOME=/usr/local/jdk
   #export PATH=$PATH:$JAVA_HOME/bin
   #export CLASSPATH=$JAVA_HOME/jre/bin/lib/ext:$JAVA_HOME/lib/tools.jar
}

function goagnent() {
    
}

function main() {
    #init_workspace
    #install_prerequisite_soft
    #get_github_code
    #set_vim
    #set_profile
    #install_font
    #install_jdk
    install_goagnent
}

main
