#!/bin/bash

ProDir=`pwd`
PathDir="set path+=""$ProDir""/**"
#create tags file
find . -type f > cscope.files
ctags --fields=+lS -L cscope.files

#create cscope file
cscope -bq

# generate tag file for lookupfile plugin
echo -e "!_TAG_FILE_SORTED\t2\t/2=foldcase/" > filenametags
find . -not -regex '.*\.\(png\|gif\)' -type f -printf "%f\t%p\t1\n" | \
    sort -f >> filenametags 

#create workspace.vim
cat <<WORKSPACE >workspace.vim

  if filereadable("./filenametags")
    let g:LookupFile_TagExpr = '"./filenametags"'
  endif
  $PathDir
  if filereadable("session.vim")
    source session.vim
  endif
  if filereadable("session.viminfo")
    rviminfo session.viminfo
  endif

WORKSPACE

